In [143]:
import numpy as np

In [144]:
arr = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

In [145]:
arr

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [146]:
arr.dtype

dtype('int64')

In [147]:
arr.shape

(3, 1, 3)

In [148]:
arr.ndim

3

In [149]:
arr [0]

array([[1, 2, 3]])

In [150]:
arr[1]

array([[4, 5, 6]])

In [151]:
arr[2]

array([[7, 8, 9]])

In [152]:
print(np.sum(arr, axis = 0))

[[12 15 18]]


In [153]:
print(np.sum(arr, axis = 2))

[[ 6]
 [15]
 [24]]


In [154]:
arr[0]

array([[1, 2, 3]])

In [155]:
arr[1]

array([[4, 5, 6]])

In [156]:
arr[2]

array([[7, 8, 9]])

In [199]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype('int32'))
print(ar)

NameError: name 'dtype' is not defined

In [193]:
ar.dtype

dtype('int64')

In [158]:
ar[0][0]#ar[0,0]

np.int64(1)

In [159]:
ar[0][1]#ar[0,1]

np.int64(2)

In [160]:
ar[0][2]#ar[0,2]

np.int64(3)

In [161]:
ar[1][0]#ar[1,0]

np.int64(4)

In [162]:
ar[1][1]#ar[1,1]

np.int64(5)

In [163]:
ar[1][2]#ar[1,2]

np.int64(6)

In [164]:
ar[2][0]#ar[2,0]

np.int64(7)

In [165]:
ar[2][1]#ar[2,1]

np.int64(8)

In [166]:
ar[2][2]#ar[2,2]

np.int64(9)

In [175]:
ar[0:2,2:3]

array([[3],
       [6]])

In [181]:
ar[1:2,2:4]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[6]])

In [186]:
ar[2:3,2:5]

array([[9]])

In [192]:
print(ar)
ar[0:2, 1:3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])