In [18]:
import numpy as np

In [19]:
arr = np.array([1,2,3])
res = arr ** 2
print(res)

[1 4 9]


In [20]:
res + 100

array([101, 104, 109])

In [21]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
mean = arr.mean(axis = 0)
print(mean)

[4. 5. 6.]


In [24]:
std = arr.std(axis = 0)
print(std)

[2.44948974 2.44948974 2.44948974]


In [25]:
broad_casting = (arr - mean) / std

In [26]:
print(broad_casting)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [27]:
np.var(arr)

np.float64(6.666666666666667)

In [28]:
np.min(arr)

np.int64(1)

In [29]:
np.max(arr)

np.int64(9)

In [30]:
np.sum(arr)

np.int64(45)

In [32]:
np.prod(arr)

np.int64(362880)

In [33]:
np.median(arr)

np.float64(5.0)

In [37]:
#np.percentile(arr) Calculate the 50th percentile (median)

In [35]:
np.argmin(arr)

np.int64(0)

In [36]:
np.argmax(arr)

np.int64(8)