In [77]:
import numpy as np

In [78]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
myarr = arr.flatten()
print(myarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [80]:
myarr[0]

np.int64(1)

In [81]:
myarr[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
myarr[:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
myarr[0:12:2]

array([ 1,  3,  5,  7,  9, 11])

In [84]:
myarr[1:12:2]

array([ 2,  4,  6,  8, 10, 12])

In [85]:
ashif = myarr[3:7]
print(ashif)

[4 5 6 7]


In [86]:
myarr[3] = 100

In [87]:
print(myarr)

[  1   2   3 100   5   6   7   8   9  10  11  12]


How to make a copy

In [88]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
myarr = arr.flatten()
print(myarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [90]:
ashif = myarr[3:7].copy()
print(ashif)

[4 5 6 7]


In [91]:
ashif[0] = 44444

In [92]:
print(ashif)

[44444     5     6     7]


In [93]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
a = arr.flatten()
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [98]:
ar = [0, 5,6]
print(a[ar])

[1 6 7]


In [99]:
ah = [1,4,7]
print(a[ah])

[2 5 8]


In [101]:
d = a > 5
print(a[d])

[ 6  7  8  9 10 11 12]
