In [28]:
import numpy as np

In [29]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.full((5,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [32]:
np.eye(3,3) #ye digonal matrix generat karta hai(it's a generat of digonal matrix)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.arange(1,100,10)#ye 1 say 100 may 10 add kar kar kay print karta hai (it's a print 1 to 100 of add 10  )

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
np.linspace(1,100,5)# ye sam sapace ya same differnt karkhta hai elements of 5

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

Cheak the numpy array of shap,size,dimention and data type

In [35]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
arr.shape

(3, 3)

In [38]:
arr.size

9

In [39]:
arr.ndim

2

In [40]:
arr.dtype

dtype('int64')

In [8]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype='float32')
print(ar)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
ar.dtype

dtype('float32')

In [11]:
reshape = ar.reshape(2,6)
print(reshape)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]


In [18]:
flate = ar.flatten()
print(flate)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
