In [18]:
import numpy as np

In [19]:
a = np.array([[2,3,4],[5,6,7],[8,9,1]])
print(a)

[[2 3 4]
 [5 6 7]
 [8 9 1]]


In [20]:
a.dtype

dtype('int64')

In [21]:
b = np.array([[2,3,4],[5,6,7],[8,9,1]],dtype='float32')
print(b)

[[2. 3. 4.]
 [5. 6. 7.]
 [8. 9. 1.]]


In [22]:
b.dtype

dtype('float32')

In [23]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [24]:
a = x.reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
fancy_indexing = np.array([1,2,3,4,5,6,7,8,9])
print(fancy_indexing)

[1 2 3 4 5 6 7 8 9]


In [26]:
f = fancy_indexing

In [27]:
ind = [1,3,5,7]
print(f[ind])

[2 4 6 8]


In [29]:
f[1:8:2]


array([2, 4, 6, 8])

In [31]:
find_graterthen_50 = np.array([10,20,30,40,50,60,70,80,90,100,110,])
print(find_graterthen_50)

[ 10  20  30  40  50  60  70  80  90 100 110]


In [32]:
greater = find_graterthen_50

In [33]:
big = greater > 50
print(greater[big])

[ 60  70  80  90 100 110]
