In [47]:
import numpy as np

In [48]:
arr = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

In [49]:
arr

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [50]:
arr.dtype

dtype('int64')

In [51]:
arr.shape

(3, 1, 3)

In [52]:
arr.ndim

3

In [53]:
arr [0]

array([[1, 2, 3]])

In [54]:
arr[1]

array([[4, 5, 6]])

In [55]:
arr[2]

array([[7, 8, 9]])

In [56]:
print(np.sum(arr, axis = 0))

[[12 15 18]]


In [57]:
print(np.sum(arr, axis = 2))

[[ 6]
 [15]
 [24]]


In [58]:
arr[0]

array([[1, 2, 3]])

In [59]:
arr[1]

array([[4, 5, 6]])

In [60]:
arr[2]

array([[7, 8, 9]])

In [61]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
ar.dtype

dtype('int64')

In [63]:
ar[0][0]#ar[0,0]

np.int64(1)

In [64]:
ar[0][1]#ar[0,1]

np.int64(2)

In [65]:
ar[0][2]#ar[0,2]

np.int64(3)

In [66]:
ar[1][0]#ar[1,0]

np.int64(4)

In [67]:
ar[1][1]#ar[1,1]

np.int64(5)

In [68]:
ar[1][2]#ar[1,2]

np.int64(6)

In [69]:
ar[2][0]#ar[2,0]

np.int64(7)

In [70]:
ar[2][1]#ar[2,1]

np.int64(8)

In [71]:
ar[2][2]#ar[2,2]

np.int64(9)

In [72]:
ar[0:2,2:3]

array([[3],
       [6]])

In [73]:
ar[1:2,2:4]

array([[6]])

In [74]:
ar[2:3,2:5]

array([[9]])

In [75]:
print(ar)
ar[0:2, 1:3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [76]:
ar.dtype

dtype('int64')

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
import numpy as np

In [81]:
arr = np.array([[444,401,402],[232,567,789]])

In [82]:
print(arr)

[[444 401 402]
 [232 567 789]]


In [83]:
arr.dtype

dtype('int64')

In [87]:
x = arr.reshape(3,2)

In [88]:
print(x)

[[444 401]
 [402 232]
 [567 789]]


In [89]:
x.dtype

dtype('int64')

In [90]:
x.shape

(3, 2)

In [91]:
x.size

6

In [93]:
x.flatten()

array([444, 401, 402, 232, 567, 789])