How to make a ZIP


In [2]:
l1 = [1,2,3]

In [3]:
l2 = [4,5,6]

In [4]:
list(zip(l1 , l2))

[(1, 4), (2, 5), (3, 6)]

How to create a numpy array

In [5]:
import numpy as np

In [6]:
np.array([1,2,3])

array([1, 2, 3])

2D Array

In [7]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(arr)


[[1 2 3 4 5]
 [6 7 8 9 1]]


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(2, 5)

cheak the time python list vs numpy array

In [11]:
import numpy as np
import time


Python List

In [12]:
list1 = [1,2,3]
start = time.time()
list_squre = [x ** 2 for x in list1]
print(list_squre)
end = time.time()
print(end - start)

[1, 4, 9]
0.00025153160095214844


Numpy Arrar

In [13]:
arr = np.array([1,2,3,])
start = time.time()
numpy_squre = arr ** 2
print(numpy_squre)
end = time.time()
print(end - start)

[1 4 9]
0.0004565715789794922
